// Astro integration that finishes and checks every build (astro:build:done):
//
//  1. Publishes install/install.sh as dist/install, after checking it.
//  2. Writes dist/_headers and dist/robots.txt for Cloudflare Workers.
//  3. Checks the output matches the build mode (see verifyOutput).
//
// Any failed check throws, which fails the build.
import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { copyFile, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const INSTALL_SCRIPT = fileURLToPath(new URL("../../install/install.sh", import.meta.url));

export default function buildHooks({ siteMode, siteEnv }) {
  return {
    name: "delocal:build-hooks",
    hooks: {
      "astro:build:done": async ({ dir, pages, logger }) => {
        const outDir = fileURLToPath(dir);
        checkNothingShadowsInstall(outDir, pages);
        await publishInstallScript(outDir);
        await writeFile(path.join(outDir, "_headers"), headersFile(siteEnv));
        await writeFile(path.join(outDir, "robots.txt"), robotsFile(siteEnv));
        await verifyOutput(outDir, siteMode, siteEnv);
        logger.info(`verified ${siteMode} build (SITE_ENV=${siteEnv})`);
      },
    },
  };
}

// /install is served from a file with no extension, so no page may claim it:
// not a page route, an endpoint, a redirect or a file copied from public/.
function checkNothingShadowsInstall(outDir, pages) {
  const routed = pages
    .map((page) => page.pathname.replace(/^\/+|\/+$/g, ""))
    .filter((pathname) => pathname === "install" || pathname.startsWith("install/"));
  if (routed.length > 0) {
    throw new Error(`these routes shadow /install: ${routed.map((p) => `/${p}`).join(", ")}`);
  }
  for (const name of ["install", "install.html"]) {
    if (existsSync(path.join(outDir, name))) {
      throw new Error(`${name} already exists in the build output and would shadow /install (is it in public/?)`);
    }
  }
}

async function publishInstallScript(outDir) {
  const script = await readFile(INSTALL_SCRIPT, "utf8");
  if (!script.startsWith("#!/bin/sh")) {
    throw new Error("install/install.sh must start with #!/bin/sh");
  }
  if (/<(!doctype|html|head|body)[\s>]/i.test(script)) {
    throw new Error("install/install.sh contains HTML");
  }
  const syntax = spawnSync("sh", ["-n", INSTALL_SCRIPT], { encoding: "utf8" });
  if (syntax.error) throw syntax.error;
  if (syntax.status !== 0) {
    throw new Error(`sh -n install/install.sh failed:\n${syntax.stderr}`);
  }
  await copyFile(INSTALL_SCRIPT, path.join(outDir, "install"));
}

// Workers applies every _headers rule that matches a path and joins the
// values, so a header must never be set by two rules whose paths overlap.
// "/*" overlaps everything: nothing it sets may appear in another rule.
function headersFile(siteEnv) {
  const everywhere = [
    "X-Content-Type-Options: nosniff",
    "Referrer-Policy: strict-origin-when-cross-origin",
    "X-Frame-Options: DENY",
    "Permissions-Policy: camera=(), microphone=(), geolocation=()",
  ];
  if (siteEnv === "preview") everywhere.push("X-Robots-Tag: noindex, nofollow");

  const rules = [
    ["/*", everywhere],
    [
      "/install",
      [
        "Content-Type: text/plain; charset=utf-8",
        "Cache-Control: public, max-age=300",
        "Content-Disposition: inline",
      ],
    ],
    ["/_astro/*", ["Cache-Control: public, max-age=31536000, immutable"]],
  ];
  const body = rules.map(([pattern, headers]) => [pattern, ...headers.map((h) => `  ${h}`)].join("\n"));
  return `# Generated by src/lib/build-hooks.mjs. Do not edit.\n${body.join("\n\n")}\n`;
}

function robotsFile(siteEnv) {
  return `User-agent: *\n${siteEnv === "preview" ? "Disallow: /" : "Allow: /"}\n`;
}

async function verifyOutput(outDir, siteMode, siteEnv) {
  const files = await listFiles(outDir);
  const pages = files.filter((file) => file.endsWith(".html"));
  const problems = [];

  if (siteMode === "holding") {
    const extra = pages.filter((page) => page !== "index.html" && page !== "404.html");
    if (extra.length > 0) problems.push(`holding build has pages besides index.html and 404.html: ${extra.join(", ")}`);
    for (const page of ["index.html", "404.html"]) {
      if (!pages.includes(page)) problems.push(`holding build is missing ${page}`);
    }
    if (existsSync(path.join(outDir, "pagefind"))) problems.push("holding build has a pagefind directory");
  } else if (!pages.includes("docs/index.html")) {
    problems.push("full build is missing docs/index.html");
  }

  for (const file of files.filter((f) => f.endsWith(".html") || f.endsWith(".css"))) {
    const text = await readFile(path.join(outDir, file), "utf8");
    for (const url of externalResources(text)) problems.push(`${file} loads ${url} from another host`);
    if (siteEnv === "production" && file.endsWith(".html") && hasPlaceholder(text)) {
      problems.push(`${file} has placeholder copy, which a production build must not ship`);
    }
  }

  if (problems.length > 0) {
    throw new Error(`build output check failed:\n  - ${problems.join("\n  - ")}`);
  }
}

// Paths relative to outDir, with forward slashes.
async function listFiles(outDir) {
  const entries = await readdir(outDir, { recursive: true, withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => path.relative(outDir, path.join(entry.parentPath, entry.name)).split(path.sep).join("/"))
    .sort();
}

// <p class="ph">[Placeholder: ...]</p>, or either half of it.
function hasPlaceholder(html) {
  if (html.includes("[Placeholder")) return true;
  for (const match of html.matchAll(/\sclass\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))/gi)) {
    const value = match[1] ?? match[2] ?? match[3];
    if (value.split(/\s+/).includes("ph")) return true;
  }
  return false;
}

// Everything is self-hosted: nothing may load a script, stylesheet, font or
// image from another host. Links (<a href>, canonical and so on) are fine.
const FETCHING_LINK_RELS = /\brel\s*=\s*["']?[^"'>]*\b(stylesheet|preload|modulepreload|prefetch|preconnect|dns-prefetch|icon|apple-touch-icon|manifest)\b/i;
const OTHER_HOST = /^\s*(?:[a-z][a-z0-9+.-]*:)?\/\//i;

function externalResources(text) {
  const urls = [];
  for (const [tag] of text.matchAll(/<(?:script|img|source|video|audio|iframe|embed|link|image|use)\b[^>]*>/gi)) {
    const isLink = /^<link\b/i.test(tag);
    if (isLink && !FETCHING_LINK_RELS.test(tag)) continue;
    for (const match of tag.matchAll(/\s(src|href|xlink:href|srcset)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))/gi)) {
      const value = match[2] ?? match[3] ?? match[4];
      const candidates = match[1].toLowerCase() === "srcset" ? value.split(",").map((s) => s.trim().split(/\s+/)[0]) : [value];
      urls.push(...candidates.filter((url) => OTHER_HOST.test(url)));
    }
  }
  for (const match of text.matchAll(/url\(\s*(['"]?)([^'")]*)\1\s*\)|@import\s+(['"])([^'"]*)\3/gi)) {
    const url = match[2] ?? match[4];
    if (OTHER_HOST.test(url)) urls.push(url);
  }
  return urls;
}
